import { describe, it, expect } from 'vitest'
import { generateEmailBody } from '../generateReport'

describe('generateEmailBody', () => {
  const mockMetrics = {
    citations: {
      total: 150,
      rate: 34,
      uniqueSources: 8,
      byEngine: [
        { engine: 'ChatGPT', citations: 80, share: 53 },
        { engine: 'Perplexity', citations: 50, share: 33 },
        { engine: 'Gemini', citations: 20, share: 14 },
      ],
    },
    overallScore: 72,
    prompts: { total: 440 },
    pages: [
      { pageTitle: 'Home', pageUrl: '/home', citations: 40 },
      { pageTitle: 'About', pageUrl: '/about', citations: 30 },
    ],
  }

  it('returns fallback when metrics is null', () => {
    expect(generateEmailBody(null, 'Test', '7d')).toBe('No metrics data available.')
  })

  it('returns fallback when metrics is undefined', () => {
    expect(generateEmailBody(undefined, 'Test', '7d')).toBe('No metrics data available.')
  })

  it('includes project name and date range label', () => {
    const result = generateEmailBody(mockMetrics, 'My Site', '30d')
    expect(result).toContain('My Site')
    expect(result).toContain('Last 30 Days')
  })

  it('maps all date range keys correctly', () => {
    expect(generateEmailBody(mockMetrics, 'P', 'today')).toContain('Today')
    expect(generateEmailBody(mockMetrics, 'P', '7d')).toContain('Last 7 Days')
    expect(generateEmailBody(mockMetrics, 'P', '30d')).toContain('Last 30 Days')
    expect(generateEmailBody(mockMetrics, 'P', '90d')).toContain('Last 90 Days')
  })

  it('falls back to "Last 7 Days" for unknown range', () => {
    const result = generateEmailBody(mockMetrics, 'P', 'unknown')
    expect(result).toContain('Last 7 Days')
  })

  it('includes summary metrics', () => {
    const result = generateEmailBody(mockMetrics, 'Test', '7d')
    expect(result).toContain('Total Citations: 150')
    expect(result).toContain('Citation Rate: 34%')
    expect(result).toContain('Unique Sources: 8')
    expect(result).toContain('AEO Score: 72/100')
    expect(result).toContain('Queries Tracked: 440')
  })

  it('lists engine citations sorted by count', () => {
    const result = generateEmailBody(mockMetrics, 'Test', '7d')
    const chatgptIdx = result.indexOf('ChatGPT')
    const perplexityIdx = result.indexOf('Perplexity')
    const geminiIdx = result.indexOf('Gemini')
    expect(chatgptIdx).toBeLessThan(perplexityIdx)
    expect(perplexityIdx).toBeLessThan(geminiIdx)
  })

  it('handles empty metrics gracefully', () => {
    const result = generateEmailBody({}, 'Empty', '7d')
    expect(result).toContain('Total Citations: 0')
    expect(result).toContain('AEO Score: 0/100')
    expect(result).toContain('No data')
  })

  it('includes top pages', () => {
    const result = generateEmailBody(mockMetrics, 'Test', '7d')
    expect(result).toContain('Home')
    expect(result).toContain('/home')
    expect(result).toContain('About')
  })

  it('ends with generator attribution', () => {
    const result = generateEmailBody(mockMetrics, 'Test', '7d')
    expect(result).toContain('Generated by AEO Dashboard')
  })
})
